version: '3'
services:
  seeder:
    image: node:8.10.0-alpine
    working_dir: /app
    command: docker/setup-dynamodb
    depends_on:
      - dynamodb
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=test
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    volumes:
      - ..:/app

  dynamodb:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -inMemory
    ports:
      - '8000:8000'
